version: '3.8'
services:
  gateway:
    build:
      context: gateway/
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
      - db-gateway
    environment:
      - POSTME_SERVER_URL=http://server:9090
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-gateway:5432/postme
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  db-gateway:
    image: postgres:13.7-alpine
    container_name: postgresql-gateway
    ports:
      - "6542:5432"

    environment:
      - POSTGRES_DB=postme
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  server:
    build:
      context: server/
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-server:5432/shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  db-server:
    image: postgres:13.7-alpine
    container_name: postgresql-server
    ports:
      - "6541:5432"

    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
