version: '3.8'
services:
  gateway:
    build:
      context: gateway/
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
    environment:
      - POSTME_SERVER_URL=http://localhost:9090

  server:
    build:
      context: server/
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  db:
    image: postgres:13.7-alpine
    container_name: postgresql
    ports:
      - "6541:5432"

    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root