version: '3.1'
services:
  gateway:
    build:
      context: gateway/
      dockerfile: Dockerfile
    container_name: gateway
    ports:
      - "8080:8080"
    depends_on:
      - server
      - redis
    environment:
      - POSTME_SERVER_URL=http://server:9090
      - API_REDIS_HOST=redis

  redis:
    image: redis:7.2.1-alpine
    container_name: redis
    ports:
      - "6379:6379"
    environment:
      - REDIS_HOST=redis
      - REDIS_PASSWORD=root

  server:
    build:
      context: server/
      dockerfile: Dockerfile
    container_name: server
    ports:
      - "9090:9090"
    depends_on:
      - db-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db-server:5432/shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root

  db-server:
    image: postgres:14-alpine
    container_name: postgresql-server
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=shareit
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
