create table if not exists USERS
(
    USER_ID BIGINT generated by default as identity not null,
    NAME    VARCHAR(255) NOT NULL,
    EMAIL   VARCHAR(200) NOT NULL,
    constraint UQ_USER_EMAIL UNIQUE (EMAIL),
    constraint USERS_PK
        primary key (USER_ID)
);

create table if not exists FRIEND_REQUESTS
(
    REQUEST_ID                BIGINT generated by default as identity not null,
    USER_ID           BIGINT                              not null,
    SUB_ID BIGINT                              not null,
    STATUS            CHARACTER VARYING not null,
    constraint FRIEND_REQUESTS_PK
        primary key (REQUEST_ID),
    constraint FRIEND_REQUESTS_USERS_USER_ID_FK
        foreign key (USER_ID) references USERS,
    constraint FRIEND_REQUESTS_USERS_USER_ID_FK_2
        foreign key (SUB_ID) references USERS
);

create table if not exists POSTS
(
    POST_ID            BIGINT generated by default as identity not null,
    TITLE         CHARACTER VARYING not null,
    DESCRIPTION   CHARACTER VARYING not null,
    IMAGE         CHARACTER VARYING,
    CREATOR       BIGINT            not null,
    PUBLISHED TIMESTAMP WITHOUT TIME ZONE        not null,
    constraint POSTS_PK
        primary key (POST_ID),
    constraint POSTS_USERS_USER_ID_FK
        foreign key (CREATOR) references USERS
);